# environment_Linux_noVer.yml
name: DSAI_data_scraping
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - attrs
  - backcall
  - backports
  - backports.functools_lru_cache
  - beautifulsoup4
  - bleach
  - brotli
  - brotli-bin
  - bzip2
  - c-ares
  - ca-certificates
  - cached-property
  - cached_property
  - cffi
  - cycler
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - executing
  - flit-core
  - fonttools
  - freetype
  - giflib
  - grpcio
  - h5py
  - hdf5
  - icu
  - imageio
  - importlib-metadata
  - importlib_resources
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jbig
  - jedi
  - jinja2
  - joblib
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyterlab_pygments
  - jupyterlab_widgets
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgfortran
  - libgfortran5
  - libiconv
  - liblapack
  - libnghttp2
  - libopenblas
  - libpng
  - libsodium
  - libssh2
  - libtiff
  - libwebp
  - libwebp-base
  - libxcb
  - libxml2
  - libxslt
  - libzlib
  - llvm-openmp
  - lxml
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - munkres
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - notebook
  - numpy
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pandocfilters
  - parso
  - pexpect
  - pickleshare
  - pillow
  - pip
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pycparser
  - pygments
  - pyparsing
  - pyrsistent
  - python
  - python-dateutil
  - python_abi
  - pytz
  - pyzmq
  - readline
  - scikit-learn
  - scipy
  - send2trash
  - setuptools
  - soupsieve
  - sqlite
  - stack_data
  - terminado
  - testpath
  - threadpoolctl
  - tk
  - tornado
  - traitlets
  - unicodedata2
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
  - absl-py
  - appdirs
  - astunparse
  - bs4
  - cachetools
  - certifi
  - charset-normalizer
  - cssselect
  - dill
  - fake-useragent
  - flatbuffers
  - gast
  - google-auth
  - google-auth-oauthlib
  - google-pasta
  - googleapis-common-protos
  - idna
  - keras
  - keras-preprocessing
  - libclang
  - markdown
  - oauthlib
  - opt-einsum
  - parse
  - promise
  - protobuf
  - pyasn1
  - pyasn1-modules
  - pyee
  - pyppeteer
  - pyquery
  - requests
  - requests-html
  - requests-oauthlib
  - rsa
  - six
  - tensorboard
  - tensorboard-data-server
  - tensorboard-plugin-wit
  - tensorflow-datasets
  - tensorflow-metadata
  - termcolor
  - tqdm
  - typing-extensions
  - urllib3
  - w3lib
  - websockets
  - werkzeug
  - wrapt
