# environment_Linux.yml
name: DSAI_data_scraping
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.10.0
  - bleach=4.1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cffi=1.15.0
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - flit-core=3.7.1
  - fonttools=4.31.2
  - freetype=2.10.4
  - giflib=5.2.1
  - grpcio=1.45.0
  - h5py=3.6.0
  - hdf5=1.12.1
  - icu=68.1
  - imageio=2.9.0
  - importlib-metadata=4.11.3
  - importlib_resources=5.6.0
  - ipykernel=6.10.0
  - ipython=8.2.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.0
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.1.1
  - joblib=1.1.0
  - jpeg=9e
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.2.0
  - jupyter_console=6.4.3
  - jupyter_core=4.9.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.1.0
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.82.0
  - libcxx=13.0.1
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran
  - libgfortran5
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.47.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.12
  - libxslt=1.1.34
  - libzlib=1.2.11
  - llvm-openmp=13.0.1
  - lxml=4.8.0
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - munkres=1.1.4
  - nbclient=0.5.13
  - nbconvert=6.4.5
  - nbformat=5.2.0
  - ncurses=6.3
  - nest-asyncio=1.5.4
  - notebook=6.4.10
  - numpy=1.21.5
  - openjpeg=2.4.0
  - openssl=3.0.3
  - packaging=21.3
  - pandas=1.4.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=22.0.4
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.27
  - prompt_toolkit=3.0.27
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyparsing=3.0.7
  - pyrsistent=0.18.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python_abi=3.8=2_cp38
  - pytz=2022.1
  - pyzmq=22.3.0
  - readline=8.1
  - scikit-learn=1.0.2
  - scipy=1.8.0
  - send2trash=1.8.0
  - setuptools=61.2.0
  - soupsieve=2.3.1
  - sqlite=3.37.1
  - stack_data=0.2.0
  - terminado=0.13.3
  - testpath=0.6.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.1.1
  - unicodedata2=14.0.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.6.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - absl-py==1.0.0
    - appdirs==1.4.4
    - astunparse==1.6.3
    - bs4==0.0.1
    - cachetools==5.0.0
    - certifi==2021.10.8
    - charset-normalizer==2.0.12
    - cssselect==1.1.0
    - dill==0.3.4
    - fake-useragent==0.1.11
    - flatbuffers==2.0
    - gast==0.5.3
    - google-auth==2.6.2
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - googleapis-common-protos==1.56.0
    - idna==3.3
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - libclang==13.0.0
    - markdown==3.3.6
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - parse==1.19.0
    - promise==2.3
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyee==8.2.2
    - pyppeteer==1.0.2
    - pyquery==1.4.3
    - requests==2.27.1
    - requests-html==0.10.0
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - six==1.15.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-datasets==4.5.2
    - tensorflow-macos==2.8.0
    - tensorflow-metadata==1.7.0
    - tensorflow-metal==0.4.0
    - termcolor==1.1.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - tqdm==4.63.1
    - typing-extensions==4.1.1
    - urllib3==1.26.9
    - w3lib==1.22.0
    - websockets==10.3
    - werkzeug==2.1.0
    - wrapt==1.14.0
